ARG ore_version=latest

FROM env_ore:${ore_version}

# Install SWIG and python3
RUN apt-get update && apt-get upgrade -y \
  && apt-get install -f -y swig python3-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /swig

# Argument for number of cores to use while building
ARG num_cores=1

COPY ore/cmake ./cmake
COPY oreswig/OREAnalytics-SWIG ./OREAnalytics-SWIG
COPY oreswig/OREData-SWIG ./OREData-SWIG
COPY oreswig/QuantExt-SWIG ./QuantExt-SWIG
COPY oreswig/QuantLib-SWIG ./QuantLib-SWIG

ENV PYTHONPATH=/swig/OREPlus-SWIG/Python/build.release/ \
    PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/ \
    PYTHON_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/python3.9

RUN find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';'
WORKDIR /swig/OREAnalytics-SWIG/Python
RUN mkdir build.release
WORKDIR /swig/OREAnalytics-SWIG/Python/build.release
RUN cmake -DORE=/swig ..
RUN make -j ${num_cores}


  #&& cd ../../../QuantLib-SWIG/Python/test \
  #&& python3 -c "import sys, OREPlus; sys.modules['QuantLib']=OREPlus;import QuantLibTestSuite;QuantLibTestSuite.test()" \
  #&& cd ../../../QuantExt-SWIG/Python/test \
  #&& python3 -c "import sys, OREPlus; sys.modules['QuantExt']=OREPlus;import QuantExtTestSuite;QuantExtTestSuite.test()" \
  #&& cd ../../../OREData-SWIG/Python/test \
  #&& python3 -c "import sys, OREPlus; sys.modules['OREData']=OREPlus;import OREDataTestSuite;OREDataTestSuite.test()" \
  #&& cd ../../../OREAnalytics-SWIG/Python/test \
  #&& python3 -c "import sys, OREPlus; sys.modules['OREAnalytics']=OREPlus;import OREAnalyticsTestSuite;OREAnalyticsTestSuite.test()" \
  #&& cd ../../../OREPlus-SWIG/Python/test \
  #&& python3 OREPlusTestSuite.py \
  #&& cd / \
  #&& mkdir build \
  #&& mv /swig/OREPlus-SWIG/Python/build.release/OREPlus.py build \
  #&& mv /swig/OREPlus-SWIG/Python/build.release/_OREPlus.so build \
  #&& rm -rf /swig \
  #&& cd /usr/local/include \
  #&& rm -rf boost \
  #&& rm -rf orea \
  #&& rm -rf ored \
  #&& rm -rf ql \
  #&& rm -rf qle

ENV PYTHONPATH=/build