ARG ore_version=latest
ARG cmake_version=latest

FROM env_ore:${ore_version} as env_ore
FROM env_cmake:${cmake_version} as env_cmake

# Take the binaries and includes from ORE environment
COPY --from=env_ore /usr/local/lib /usr/local/lib
COPY --from=env_ore /usr/local/include /usr/local/include

# Replace apt-get cmake with local build
RUN apt remove --purge --auto-remove -y cmake
COPY --from=env_cmake /usr/local/bin/cmake /usr/local/bin/cmake

# Install SWIG and python3
RUN apt-get update \
  && apt-get install -y swig3.0 python3-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /swig

# Argument for number of cores to use while building
ARG num_cores=1

COPY OREAnalytics-SWIG ./OREAnalytics-SWIG
COPY OREData-SWIG ./OREData-SWIG
COPY QuantExt-SWIG ./QuantExt-SWIG
COPY QuantLib-SWIG ./QuantLib-SWIG
COPY cmake ./cmake

ENV PYTHONPATH=/swig/OREAnalytics-SWIG/Python/build.release/
ENV PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/
ENV PYTHON_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/python3.5m
ENV CXXFLAGS="-O2 -std=c++11 -DBOOST_MATH_DISABLE_FLOAT128"

RUN cd OREAnalytics-SWIG/Python \
  && mkdir build.release \
  && cd build.release \
  && cmake .. \
  && make -j ${num_cores} \
  && cd ../../../QuantLib-SWIG/Python/test \
  && python3 -c "import sys, OREAnalytics; sys.modules['QuantLib']=OREAnalytics;import QuantLibTestSuite;QuantLibTestSuite.test()" \
  && cd ../../../QuantExt-SWIG/Python/test \
  && python3 -c "import sys, OREAnalytics; sys.modules['QuantExt']=OREAnalytics;import QuantExtTestSuite;QuantExtTestSuite.test()" \
  && cd ../../../OREData-SWIG/Python/test \
  && python3 -c "import sys, OREAnalytics; sys.modules['OREData']=OREAnalytics;import OREDataTestSuite;OREDataTestSuite.test()" \
  && cd / \
  && rm -rf swig
