ARG ore_plus_version=latest

FROM env_ore_plus:${ore_plus_version}

# Install cmake from testing (cmake>=3.8)
# Install dos2unix, SWIG and python3
RUN echo deb http://deb.debian.org/debian testing main >> /etc/apt/sources.list \
  && apt-get update \
  && apt-get remove --purge -y cmake \
  && apt-get -t testing install -y cmake \
  && apt-get install -y swig3.0 python3-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /swig

# Argument for number of cores to use while building
ARG num_cores=1

COPY OREPlus-SWIG ./OREPlus-SWIG
COPY OREAnalytics-SWIG ./OREAnalytics-SWIG
COPY OREData-SWIG ./OREData-SWIG
COPY QuantExt-SWIG ./QuantExt-SWIG
COPY QuantLib-SWIG ./QuantLib-SWIG
COPY cmake ./cmake

ENV PYTHONPATH=/swig/OREPlus-SWIG/Python/build.release/ \
    PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/ \
    PYTHON_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/python3.5m

RUN \
  find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';' \
  && cd OREPlus-SWIG/Python \
  && mkdir build.release \
  && cd build.release \
  && cmake -DORE=../../ .. \
  && make -j ${num_cores} \
  && cd ../../../QuantLib-SWIG/Python/test \
  && python3 -c "import sys, OREPlus; sys.modules['QuantLib']=OREPlus;import QuantLibTestSuite;QuantLibTestSuite.test()" \
  && cd ../../../QuantExt-SWIG/Python/test \
  && python3 -c "import sys, OREPlus; sys.modules['QuantExt']=OREPlus;import QuantExtTestSuite;QuantExtTestSuite.test()" \
  && cd ../../../OREData-SWIG/Python/test \
  && python3 -c "import sys, OREPlus; sys.modules['OREData']=OREPlus;import OREDataTestSuite;OREDataTestSuite.test()" \
  && cd ../../../OREAnalytics-SWIG/Python/test \
  && python3 -c "import sys, OREPlus; sys.modules['OREAnalytics']=OREPlus;import OREAnalyticsTestSuite;OREAnalyticsTestSuite.test()" \
  && cd ../../../OREPlus-SWIG/Python/test \
  && python3 OREPlusTestSuite.py \
  && cd / \
  && mkdir build \
  && mv /swig/OREPlus-SWIG/Python/build.release/OREPlus.py build \
  && mv /swig/OREPlus-SWIG/Python/build.release/_OREPlus.so build \
  && rm -rf /swig \
  && cd /usr/local/include \
  && rm -rf boost \
  && rm -rf orea \
  && rm -rf ored \
  && rm -rf ql \
  && rm -rf qle

ENV PYTHONPATH=/build