ARG ore_version=latest

FROM env_ore:${ore_version}

# Install SWIG and python3
RUN apt-get update && apt-get upgrade -y \
  && apt-get install -f -y swig python3-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /swig

# Argument for number of cores to use while building
ARG num_cores=1

COPY OREAnalytics-SWIG ./OREAnalytics-SWIG
COPY OREData-SWIG ./OREData-SWIG
COPY QuantExt-SWIG ./QuantExt-SWIG
COPY QuantLib-SWIG ./QuantLib-SWIG
COPY cmake ./cmake

ENV PYTHONPATH=/swig/OREAnalytics-SWIG/Python/build.release/ \
    PYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/ \
    PYTHON_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/python3.5m

RUN \
  find -regex ".*\.\(sh\|in\|ac\|am\)" -exec dos2unix {} ';' \
  && cd OREAnalytics-SWIG/Python \
  && mkdir build.release \
  && cd build.release \
  && cmake -DORE=../../ .. \
  && make -j ${num_cores} \
  && cd ../../../QuantLib-SWIG/Python/test \
  && python3 -c "import sys, OREAnalytics; sys.modules['QuantLib']=OREAnalytics;import QuantLibTestSuite;QuantLibTestSuite.test()" \
  && cd ../../../QuantExt-SWIG/Python/test \
  && python3 -c "import sys, OREAnalytics; sys.modules['QuantExt']=OREAnalytics;import QuantExtTestSuite;QuantExtTestSuite.test()" \
  && cd ../../../OREData-SWIG/Python/test \
  && python3 -c "import sys, OREAnalytics; sys.modules['OREData']=OREAnalytics;import OREDataTestSuite;OREDataTestSuite.test()" \
  && cd ../../../OREAnalytics-SWIG/Python/test \
  && python3 OREAnalyticsTestSuite.py \
  && cd / \
  && mkdir build \
  && mv /swig/OREAnalytics-SWIG/Python/build.release/OREAnalytics.py build \
  && mv /swig/OREAnalytics-SWIG/Python/build.release/_OREAnalytics.so build \
  && rm -rf /swig \
  && cd /usr/local/include \
  && rm -rf boost \
  && rm -rf orea \
  && rm -rf ored \
  && rm -rf ql \
  && rm -rf qle

ENV PYTHONPATH=/build