#syntax = nexus3.acadiasoft.net:4445/docker/dockerfile:experimental

ARG ore_version=latest
ARG debian_tag=latest

FROM env_oreswig:${ore_version} as env_oreswig
FROM env_ore:${ore_version} as env_ore
FROM debian:${debian_tag}

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y dos2unix python3 python3-pip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN mkdir /oreswig
RUN mkdir /oreswig/pythonlib

COPY --from=env_oreswig /oreswig/ORE.py /oreswig/pythonlib/ORE.py 
COPY --from=env_oreswig /oreswig/_ORE.so /oreswig/pythonlib/_ORE.so 

COPY --from=env_ore /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu

RUN true

COPY --from=env_ore /usr/local/lib /usr/local/lib

ENV PYTHONPATH=/oreswig/pythonlib

RUN mkdir /oreswig/tests

COPY oreswig/QuantLib-SWIG/Python/test /oreswig/tests/QuantLibTestSuite
COPY oreswig/OREAnalytics-SWIG/Python/test /oreswig/tests/ORETestSuite
COPY oreswig/OREAnalytics-SWIG/Python/Examples /oreswig/examples
COPY ore/Examples /oreswig/ORE-Examples

ENV ORE_EXAMPLES_USE_PYTHON=1

CMD bash