#!/bin/sh

prefix=/Users/roland/Development/oremaster/QuantExt
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: quantext-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.13
      ;;
    --cflags)
      #echo -I${prefix}/include  
      echo -I${prefix}  -I${prefix}/../QuantLib
      ;;
    --libs)
      #echo -L${exec_prefix}/lib  -lQuantLib  
      echo -L${exec_prefix}/qle/.libs  -lQuantExt -L${exec_prefix}/../QuantLib/ql/.libs -lQuantLib
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
