#!/bin/sh

prefix=/Users/roland/Development/oremaster
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: quantlib-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.13
      ;;
    --cflags)
      #echo -I${prefix}/include  
      echo -I${prefix}/OREAnalyticsPlus -I${prefix}/OREDataPlus -I${prefix}/OREPlus/Sensitivity -I${prefix}/OREPlus/Base -I${prefix}/QuantExtPlus -I${prefix}/OREAnalytics -I${prefix}/OREData -I${prefix}/QuantExt -I${prefix}/QuantLib -I${BOOST}
      ;;
    --libs)
      #echo -L${exec_prefix}/lib  -lQuantLib  
      echo -L${exec_prefix}/OREAnalyticsPlus/oreap/.libs -lOREAnalyticsPlus -L${exec_prefix}/OREDataPlus/oredp/.libs -lOREDataPlus -L${exec_prefix}/OREPlus/Sensitivity/orepsnesi/.libs -lOREPlusSensi -L${exec_prefix}/OREPlus/Base/orepbase/.libs -lOREPlusBase -L${exec_prefix}/QuantExtPlus/qlep/.libs -lQuantExtPlus -L${exec_prefix}/OREAnalytics/orea/.libs -lOREAnalytics -L${exec_prefix}/OREData/ored/.libs -lOREData -L${exec_prefix}/QuantExt/qle/.libs -lQuantExt -L${exec_prefix}/QuantLib/ql/.libs -lQuantLib -L${BOOST}/stage/lib -lboost_thread -lboost_system -lboost_serialization -lboost_date_time -lboost_regex -lboost_filesystem
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
